[font]
size = 16.0

[font.bold]
family = "FiraCode Nerd Font Mono"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"

[font.italic]
family = "FiraCode Nerd Font Mono"

[font.normal]
family = "FiraCode Nerd Font Mono"

[window]
decorations = "full"
startup_mode = "Maximized"

[window.dimensions]
columns = 200
lines = 50

[window.position]
x = 0
y = 0
