#!/usr/bin/bash

~/.fehbg &
~/scripts/polybar_controller open &
pgrep -x brave &>/dev/null || brave &
pgrep -x st &>/dev/null || st -e tmux &
flameshot &
slack &

sleep 5
systemctl --user restart redshift &
