#!/usr/bin/env bash
close_polybar() {
  killall -p polybar 2>/dev/null
}
open_polybar(){
  close_polybar
  echo ---$(date)--- | tee -a /tmp/polybar-nebula.log
  polybar nebula 2>&1 | tee -a /tmp/polybar-nebula.log
}
case "$1" in
  "close") close_polybar
  ;;
  "open") open_polybar
  ;;
  "hide") polybar-msg cmd hide
  ;;
  "show") polybar-msg cmd show
  ;;
  "toggle") polybar-msg cmd toggle
  ;;
  *)
    open_polybar
  ;;
esac

