#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_zoom_persist on
yabai -m config window_topmost off
yabai -m config window_shadow on
yabai -m config window_animation_duration 60.0
yabai -m config window_animation_frame_rate 120
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config window_opacity off
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config active_window_border_color 0xa1fdffff
yabai -m config normal_window_border_color 0x000
yabai -m config window_border_width 2
yabai -m config window_border_radius 12
yabai -m config window_border_blur off
yabai -m config window_border_hidpi on
yabai -m config window_border on
yabai -m config split_ratio 0.50
yabai -m config split_type auto
yabai -m config auto_balance off
yabai -m config layout bsp
yabai -m config mouse_modifier cmd
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

yabai -m rule --add app="^System Settings$" manage=off

echo "yabai configuration loaded.."
